import { useReplay } from "../../context/ReplayContext";

function ReplayControls() {
  const {
      currentIndex,
          isPlaying,
              replaySpeed,
                  setReplaySpeed,
                      play,
                          pause,
                              reset,
                                  nextCandle,
                                      previousCandle,
                                        } = useReplay();

                                          return (
                                              <div className="bg-slate-800 rounded-xl p-5 border border-slate-700 mt-6">
                                                    <h2 className="text-xl font-bold text-white mb-4">
                                                            ▶ Replay Controls
                                                                  </h2>

                                                                        <div className="flex flex-wrap gap-3 items-center">

                                                                                <button
                                                                                          onClick={previousCandle}
                                                                                                    className="px-4 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-white"
                                                                                                            >
                                                                                                                      ⏮ Prev
                                                                                                                              </button>

                                                                                                                                      {!isPlaying ? (
                                                                                                                                                <button
                                                                                                                                                            onClick={play}
                                                                                                                                                                        className="px-4 py-2 bg-green-600 hover:bg-green-700 rounded-lg text-white"
                                                                                                                                                                                  >
                                                                                                                                                                                              ▶ Play
                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                      onClick={pause}
                                                                                                                                                                                                                                                  className="px-4 py-2 bg-yellow-600 hover:bg-yellow-700 rounded-lg text-white"
                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                        ⏸ Pause
                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                            onClick={nextCandle}
                                                                                                                                                                                                                                                                                                                      className="px-4 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-white"
                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                        ⏭ Next
                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                  onClick={reset}
                                                                                                                                                                                                                                                                                                                                                                            className="px-4 py-2 bg-red-600 hover:bg-red-700 rounded-lg text-white"
                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                              🔄 Reset
                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                              <select
                                                                                                                                                                                                                                                                                                                                                                                                                        value={replaySpeed}
                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setReplaySpeed(Number(e.target.value))}
                                                                                                                                                                                                                                                                                                                                                                                                                                            className="bg-slate-900 text-white border border-slate-600 rounded-lg px-3 py-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value={0.5}>0.5x</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value={1}>1x</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value={2}>2x</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value={5}>5x</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value={10}>10x</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-5 text-slate-300 space-y-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>Current Candle: {currentIndex + 1}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Status: {isPlaying ? "🟢 Playing" : "⏸ Paused"}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>Speed: {replaySpeed}x</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default ReplayControls;