import { useReplay } from "../../hooks/useReplay";

function ReplayControls() {
  const {
      replay,
          play,
              pause,
                  next,
                      previous,
                          reset,
                              changeSpeed,
                                } = useReplay();

                                  return (
                                      <div className="bg-slate-800 rounded-xl border border-slate-700 p-5 mt-8">
                                            <h2 className="text-white text-xl font-bold mb-5">
                                                    ▶ Replay Controls
                                                          </h2>

                                                                <div className="flex flex-wrap gap-3">

                                                                        <button
                                                                                  onClick={play}
                                                                                            className="bg-green-600 hover:bg-green-700 px-5 py-2 rounded text-white"
                                                                                                    >
                                                                                                              ▶ Play
                                                                                                                      </button>

                                                                                                                              <button
                                                                                                                                        onClick={pause}
                                                                                                                                                  className="bg-yellow-600 hover:bg-yellow-700 px-5 py-2 rounded text-white"
                                                                                                                                                          >
                                                                                                                                                                    ⏸ Pause
                                                                                                                                                                            </button>

                                                                                                                                                                                    <button
                                                                                                                                                                                              onClick={previous}
                                                                                                                                                                                                        className="bg-slate-600 hover:bg-slate-500 px-5 py-2 rounded text-white"
                                                                                                                                                                                                                >
                                                                                                                                                                                                                          ⏮ Prev
                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                    onClick={next}
                                                                                                                                                                                                                                                              className="bg-blue-600 hover:bg-blue-700 px-5 py-2 rounded text-white"
                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                ⏭ Next
                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                          onClick={reset}
                                                                                                                                                                                                                                                                                                                    className="bg-red-600 hover:bg-red-700 px-5 py-2 rounded text-white"
                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                      🔄 Reset
                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                      <select
                                                                                                                                                                                                                                                                                                                                                                value={replay.speed}
                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => changeSpeed(Number(e.target.value))}
                                                                                                                                                                                                                                                                                                                                                                                    className="bg-slate-700 text-white rounded px-3"
                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                      <option value={1}>1x</option>
                                                                                                                                                                                                                                                                                                                                                                                                                <option value={2}>2x</option>
                                                                                                                                                                                                                                                                                                                                                                                                                          <option value={5}>5x</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value={10}>10x</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-5 text-slate-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Current Candle: {replay.currentIndex}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Status: {replay.isPlaying ? "▶ Playing" : "⏸ Paused"}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Speed: {replay.speed}x</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default ReplayControls;