import { useRef } from "react";
import Section from "../ui/Section";
import { useCSVImport } from "../../hooks/useCSVImport";

function ImportCSV() {
  const {
      selectedFile,
          fileSize,
              totalLines,
                  preview,
                      candles,
                          stats,
                              importCSV,
                                } = useCSVImport();

                                  const fileInputRef = useRef<HTMLInputElement>(null);

                                    function handleFileChange(event: React.ChangeEvent<HTMLInputElement>) {
                                        const file = event.target.files?.[0];

                                            if (!file) return;

                                                importCSV(file);
                                                  }

                                                    function openFilePicker() {
                                                        fileInputRef.current?.click();
                                                          }

                                                            return (
                                                                <Section title="📥 Import CSV">
                                                                      <input
                                                                              ref={fileInputRef}
                                                                                      type="file"
                                                                                              accept=".csv"
                                                                                                      onChange={handleFileChange}
                                                                                                              style={{ display: "none" }}
                                                                                                                    />

                                                                                                                          <div
                                                                                                                                  onClick={openFilePicker}
                                                                                                                                          className="bg-slate-800 border-2 border-dashed border-slate-600 hover:border-blue-500 hover:bg-slate-700 rounded-xl p-10 cursor-pointer transition-all duration-300 text-center"
                                                                                                                                                >
                                                                                                                                                        <div className="text-6xl mb-4">📂</div>

                                                                                                                                                                <h3 className="text-white text-2xl font-bold mb-3">
                                                                                                                                                                          Click Anywhere to Import CSV
                                                                                                                                                                                  </h3>

                                                                                                                                                                                          <p className="text-slate-400">
                                                                                                                                                                                                    Import your Dukascopy or supported CSV file
                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                    <p className="text-slate-500 mt-2">
                                                                                                                                                                                                                              Supported format: .csv
                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                              {selectedFile && (
                                                                                                                                                                                                                                                        <div className="mt-6 text-left bg-slate-900 rounded-lg p-4">
                                                                                                                                                                                                                                                                    <p className="text-green-400 font-semibold">
                                                                                                                                                                                                                                                                                  ✅ {selectedFile.name}
                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                          <p className="text-slate-300 mt-2">
                                                                                                                                                                                                                                                                                                                        📦 Size: {fileSize}
                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                <p className="text-slate-300">
                                                                                                                                                                                                                                                                                                                                                              📄 Total Lines: {totalLines}
                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-slate-300">
                                                                                                                                                                                                                                                                                                                                                                                                    📈 Parsed Candles: {candles.length}
                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                            {stats && (
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-5 border-t border-slate-700 pt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-blue-400 font-bold mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            📊 CSV Statistics
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-slate-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              🕒 First Candle: {String(stats.firstCandle)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-slate-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                🕒 Last Candle: {String(stats.lastCandle)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-slate-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  📈 Highest High: {stats.highestHigh}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-slate-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    📉 Lowest Low: {stats.lowestLow}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-slate-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      📊 Average Volume: {stats.averageVolume.toFixed(2)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-slate-400 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Preview (First 5 Lines)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <pre className="bg-black text-green-400 p-3 rounded overflow-auto text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {preview}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </pre>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default ImportCSV;